<font size="2">
<p><strong>Seções<br></strong></p>
<p><a hef="cartaz.php">EM CARTAZ</a></p>
<p><a hef="destaques.php">DESTAQUES</a></p>
<p><a hef="breve.php">EM BREVE</a></p>
<p><a hef="ranking.php">RANKING</a></p>
<p><a hef="trailer.php">TRAILER</a></p>
<p><a hef="bilheteria.php">BILHETERIA</a></p>
<p><a hef="programacao.php">PROGRAMACAO</a></p>
<p><a hef="fotos.php">FOTOS</a></p>
<p><a hef="links.php">LINKS</a></p>
<p><a hef="arquivos.php">ARQUIVOS</a></p>
<p><a hef="opiniao.php">OPINIAO</a></p>
</font>